# Generated by Django 4.0.6 on 2022-08-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathmapping',
            name='accessed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
