# Generated by Django 4.0.6 on 2022-08-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_pathmapping_accessed'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathmapping',
            name='message_id',
            field=models.CharField(db_index=True, default=12, max_length=64),
            preserve_default=False,
        ),
    ]
