# Generated by Django 4.0.6 on 2022-08-03 05:23

from django.db import migrations, models
import storage.storages


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(storage=storage.storages.TelegramStorage, upload_to='files')),
            ],
        ),
    ]
